config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :projects do
    resources :items, except: [:destroy]
    delete "clear", on: :member
  end
  root "projects#index"
end

app/models/item.rb
# frozen_string_literal: true
class Item < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :project

  validates :action,
    presence: true,
    uniqueness: { scope: :project,
                     message: "should be unique within a project" }
  validates :project_id, presence: true

  scope :complete, -> { where(done: true) }
  scope :incomplete, -> { where(done: false) }

  delegate :title, to: :project, prefix: true
end

app/models/project.rb
# frozen_string_literal: true
class Project < ActiveRecord::Base
  acts_as_paranoid

  validates :title, presence: true, uniqueness: true

  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true
require "csv"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Record not found" }
      format.json {  render json: nil, status: :not_found }
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true
class ItemsController < ApplicationController
  before_action :get_project
  before_action :get_item, only: [:edit, :show, :update]

  def index
    respond_to do |format|
      format.csv do
        headers["Content-Disposition"] = "attachment; filename=\"project-#{@project.id}-items.csv\""
        headers["Content-Type"] ||= "text/csv"
        @items = CompletedItem.filter(
          project: @project,
          status: params[:item][:status]
        )
      end
    end
  end

  def new
    @item = @project.items.build
  end

  def create
    @item = @project.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to project_path(@project),
                      notice: "Item was successfully created."
        }
        format.json { render :show, status: :created, location: [@project, @item] }
      else
        format.html { render "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
    respond_to do |format|
      format.html { redirect_to @project }
      format.json { render :show, status: :ok, location: [@project, @item] }
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to project_path(@project),
                      notice: "Item was successfully updated."
        }
        format.json { render :show, status: :ok, location: [@project, @item] }
      else
        format.html { render "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def get_project
    @project = Project.find(params[:project_id])
  end

  def get_item
    @item = @project.items.find params[:id]
  end

  def item_params
    params.require(:item).permit(:action, :done)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true
class ProjectsController < ApplicationController
  before_action :set_project, except: [:index, :new, :create]

  def index
    @projects = Project.all
    respond_to do |format|
      format.csv do
        headers["Content-Disposition"] = "attachment; filename=\"projects.csv\""
        headers["Content-Type"] ||= "text/csv"
        @items = CompletedItem.all
      end
      format.html
      format.json
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project),
                      notice: "Project was successfully created."
        }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project),
                      notice: "Project was successfully updated."
        }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path,
                    notice: "Project was successfully destroyed."
      }
      format.json { head :no_content }
    end
  end

  def clear
    @project.items.complete.destroy_all
    respond_to do |format|
      format.html { redirect_to project_path(@project),
                    notice: "There are no completed items for this project."
      }
      format.json { render :show, status: :updated, location: @project }
    end
  end

private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
end

app/views/items/_index.html.erb
<ul id="project-items">
  <% if project.items.empty? %>
  <li>No items.</li>
  <% end %>
<% project.items.each do |item| %>
  <li class="<%= "item-#{item.to_param}" %> <%= "#{ 'done' if item.done? }" %>">
    <%= check_box_tag "item-done-#{item.to_param}", item.id, item.done? %>
    <%= item.action -%>
    <span><%= link_to 'edit', edit_project_item_path(project, item) %></span>
  </li>
<% end %>
</ul>

<%= link_to "New Item", new_project_item_path(project) %>
<%= button_to "Clear Completed Items", clear_project_path(project),
      :method => :delete, :id => "clearer" %>

app/views/items/_item.csv.erb
<%= CSV.generate_line([item.project_title, item.action, item.done]) -%>

app/views/items/edit.html.erb
<h2>Edit Item</h2>
<%= form_for([@project, @item], :url => { :action => :update }) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action, :size => "80" %>
  </div>
  <br />

  <div class="field">
    <%= f.label :done, 'Done?' %>
    <%= f.check_box :done %>
  </div>
  <br />

  <div class="actions">
    <%= f.submit %>
  </div>
  <%= link_to 'Back', @project %>
<% end %>

app/views/items/index.csv.erb
<%- headers = ["Project Title", "Action", "Done"] -%>
<%= CSV.generate_line headers, row_sep: ?\t %>
<%= render @items %>

app/views/items/new.html.erb
<h2>New Item</h2>
<%= form_for([@project, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action, :size => "80" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--[if lt IE 9]>
    <script src="http://html5.shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>Todo App</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <h1>Todo app</h1>
      <nav>
        <ul>
          <li><%= link_to 'Projects', projects_path %></li>
        </ul>
      </nav>
    </header>

    <div id="main">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <footer>
      <p><%= Date.today.year %></p>
    </footer>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(project.errors.count, "error") %>
        prohibited this project from being saved:
      </h2>

      <ul>
      <% project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :size => "80" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render 'form', project: @project %>

app/views/projects/index.csv.erb
<%- headers = ["Project Title", "Action", "Done"] -%>
<%= CSV.generate_line headers, row_sep: ?\t %>
<%= render partial: 'items/item', collection: @items %>

app/views/projects/index.html.erb
<div>
  <%= link_to 'Download Completed Items CSV', projects_path(format: :csv), class: "csv-export" %>
</div>

<h2>Projects</h2>

<br class="clearfix" />

<ul>
  <% if @projects.empty? %>
  <li>No projects.</li>
  <% end %>
<% @projects.each do |project| %>
<li>
  <%= link_to project.title,  project_path(project) %>
  <span>
    <%= link_to 'Destroy', project,
                method: :delete, data: { confirm: 'Are you sure?' } %>
  </span>
</li>
<% end %>
</ul>

<div>
  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div>
<%= form_tag(project_items_path(@project, format: :csv), { class: "csv-export", method: "get" }) do %>
  <div>
    <%= radio_button("item", "status", "all", { checked: true }) %>
    <%= label_tag "item_status_all", "All" %>
    <%= radio_button("item", "status", "done") %>
    <%= label_tag "item_status_done", "Done" %>
    <%= radio_button("item", "status", "pending") %>
    <%= label_tag "item_status_pending", "Not Done" %>
  </div>
  <%= submit_tag 'Download Items CSV' %>
<% end -%>
</div>

<h2><%= link_to @project.title, edit_project_path(@project) %> Items</h2>

<br class="clearfix" />

<%= render :partial => 'items/index', :locals => { project: @project } %>